http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
add.interactive.usebuiltin=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
pull.rebase=false
winupdater.recentlyseenversion=2.28.0.windows.1
core.editor=code --wait
core.safecrlf=false
user.name=Akanksha242
user.email=akankshapandey242@gmail.com
color.ui=true
merge.conflictstyle=diff3
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/Akanksha242/PalindromeSimulator.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
